// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package errx

import (
	"fmt"
)

const (
	// Unknown error (default/zero value)
	CodeUnknown Code = 0
	// Operation canceled by caller
	CodeCanceled Code = 1
	// Request is invalid, regardless of system state
	CodeInvalidArgument Code = 2
	// Deadline expired before operation completed
	CodeDeadlineExceeded Code = 3
	// Requested resource cannot be found
	CodeNotFound Code = 4
	// Resource already exists
	CodeAlreadyExists Code = 5
	// Caller isn't authorized
	CodePermissionDenied Code = 6
	// Resource exhausted (quota, storage, etc.)
	CodeResourceExhausted Code = 7
	// System isn't in required state
	CodeFailedPrecondition Code = 8
	// Operation aborted (concurrency issue)
	CodeAborted Code = 9
	// Operation attempted past valid range
	CodeOutOfRange Code = 10
	// Operation not implemented/supported
	CodeUnimplemented Code = 11
	// Internal error (invariant broken)
	CodeInternal Code = 12
	// Service temporarily unavailable
	CodeUnavailable Code = 13
	// Unrecoverable data loss or corruption
	CodeDataLoss Code = 14
	// Valid authentication credentials required
	CodeUnauthenticated Code = 15
)

const _CodeName = "unknowncanceledinvalid_argumentdeadline_exceedednot_foundalready_existspermission_deniedresource_exhaustedfailed_preconditionabortedout_of_rangeunimplementedinternalunavailabledata_lossunauthenticated"

var _CodeNames = []string{
	_CodeName[0:7],
	_CodeName[7:15],
	_CodeName[15:31],
	_CodeName[31:48],
	_CodeName[48:57],
	_CodeName[57:71],
	_CodeName[71:88],
	_CodeName[88:106],
	_CodeName[106:125],
	_CodeName[125:132],
	_CodeName[132:144],
	_CodeName[144:157],
	_CodeName[157:165],
	_CodeName[165:176],
	_CodeName[176:185],
	_CodeName[185:200],
}

// CodeNames returns a list of possible string values of Code.
func CodeNames() []string {
	tmp := make([]string, len(_CodeNames))
	copy(tmp, _CodeNames)
	return tmp
}

// CodeValues returns a list of the values for Code
func CodeValues() []Code {
	return []Code{
		CodeUnknown,
		CodeCanceled,
		CodeInvalidArgument,
		CodeDeadlineExceeded,
		CodeNotFound,
		CodeAlreadyExists,
		CodePermissionDenied,
		CodeResourceExhausted,
		CodeFailedPrecondition,
		CodeAborted,
		CodeOutOfRange,
		CodeUnimplemented,
		CodeInternal,
		CodeUnavailable,
		CodeDataLoss,
		CodeUnauthenticated,
	}
}

var _CodeMap = map[Code]string{
	CodeUnknown:            _CodeName[0:7],
	CodeCanceled:           _CodeName[7:15],
	CodeInvalidArgument:    _CodeName[15:31],
	CodeDeadlineExceeded:   _CodeName[31:48],
	CodeNotFound:           _CodeName[48:57],
	CodeAlreadyExists:      _CodeName[57:71],
	CodePermissionDenied:   _CodeName[71:88],
	CodeResourceExhausted:  _CodeName[88:106],
	CodeFailedPrecondition: _CodeName[106:125],
	CodeAborted:            _CodeName[125:132],
	CodeOutOfRange:         _CodeName[132:144],
	CodeUnimplemented:      _CodeName[144:157],
	CodeInternal:           _CodeName[157:165],
	CodeUnavailable:        _CodeName[165:176],
	CodeDataLoss:           _CodeName[176:185],
	CodeUnauthenticated:    _CodeName[185:200],
}

// String implements the Stringer interface.
func (x Code) String() string {
	if str, ok := _CodeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Code(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Code) IsValid() bool {
	_, ok := _CodeMap[x]
	return ok
}

var _CodeValue = map[string]Code{
	_CodeName[0:7]:     CodeUnknown,
	_CodeName[7:15]:    CodeCanceled,
	_CodeName[15:31]:   CodeInvalidArgument,
	_CodeName[31:48]:   CodeDeadlineExceeded,
	_CodeName[48:57]:   CodeNotFound,
	_CodeName[57:71]:   CodeAlreadyExists,
	_CodeName[71:88]:   CodePermissionDenied,
	_CodeName[88:106]:  CodeResourceExhausted,
	_CodeName[106:125]: CodeFailedPrecondition,
	_CodeName[125:132]: CodeAborted,
	_CodeName[132:144]: CodeOutOfRange,
	_CodeName[144:157]: CodeUnimplemented,
	_CodeName[157:165]: CodeInternal,
	_CodeName[165:176]: CodeUnavailable,
	_CodeName[176:185]: CodeDataLoss,
	_CodeName[185:200]: CodeUnauthenticated,
}

// NewUnknown creates a new error of type Unknown with the given message.
func NewUnknown(msg string) *Error {
	return newError(CodeUnknown, msg, nil)
}

// NewfUnknown creates a new error of type Unknown with a formatted message.
func NewfUnknown(format string, args ...any) *Error {
	return newError(CodeUnknown, fmt.Sprintf(format, args...), nil)
}

// WrapUnknown wraps an existing error of type Unknown with the given message.
func WrapUnknown(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnknown, msg, err)
}

// WrapfUnknown wraps an existing error of type Unknown with a formatted message.
func WrapfUnknown(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnknown, fmt.Sprintf(format, args...), err)
}

// EnsureUnknown ensures the error is an *Error, falling back to Unknown with the given message.
func EnsureUnknown(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnknown, msg, err)
}

// EnsurefUnknown ensures the error is an *Error, falling back to Unknown with a formatted message.
func EnsurefUnknown(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnknown, fmt.Sprintf(format, args...), err)
}

// NewCanceled creates a new error of type Canceled with the given message.
func NewCanceled(msg string) *Error {
	return newError(CodeCanceled, msg, nil)
}

// NewfCanceled creates a new error of type Canceled with a formatted message.
func NewfCanceled(format string, args ...any) *Error {
	return newError(CodeCanceled, fmt.Sprintf(format, args...), nil)
}

// WrapCanceled wraps an existing error of type Canceled with the given message.
func WrapCanceled(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeCanceled, msg, err)
}

// WrapfCanceled wraps an existing error of type Canceled with a formatted message.
func WrapfCanceled(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeCanceled, fmt.Sprintf(format, args...), err)
}

// EnsureCanceled ensures the error is an *Error, falling back to Canceled with the given message.
func EnsureCanceled(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeCanceled, msg, err)
}

// EnsurefCanceled ensures the error is an *Error, falling back to Canceled with a formatted message.
func EnsurefCanceled(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeCanceled, fmt.Sprintf(format, args...), err)
}

// NewInvalidArgument creates a new error of type Invalid_argument with the given message.
func NewInvalidArgument(msg string) *Error {
	return newError(CodeInvalidArgument, msg, nil)
}

// NewfInvalidArgument creates a new error of type Invalid_argument with a formatted message.
func NewfInvalidArgument(format string, args ...any) *Error {
	return newError(CodeInvalidArgument, fmt.Sprintf(format, args...), nil)
}

// WrapInvalidArgument wraps an existing error of type Invalid_argument with the given message.
func WrapInvalidArgument(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeInvalidArgument, msg, err)
}

// WrapfInvalidArgument wraps an existing error of type Invalid_argument with a formatted message.
func WrapfInvalidArgument(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeInvalidArgument, fmt.Sprintf(format, args...), err)
}

// EnsureInvalidArgument ensures the error is an *Error, falling back to Invalid_argument with the given message.
func EnsureInvalidArgument(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeInvalidArgument, msg, err)
}

// EnsurefInvalidArgument ensures the error is an *Error, falling back to Invalid_argument with a formatted message.
func EnsurefInvalidArgument(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeInvalidArgument, fmt.Sprintf(format, args...), err)
}

// NewDeadlineExceeded creates a new error of type Deadline_exceeded with the given message.
func NewDeadlineExceeded(msg string) *Error {
	return newError(CodeDeadlineExceeded, msg, nil)
}

// NewfDeadlineExceeded creates a new error of type Deadline_exceeded with a formatted message.
func NewfDeadlineExceeded(format string, args ...any) *Error {
	return newError(CodeDeadlineExceeded, fmt.Sprintf(format, args...), nil)
}

// WrapDeadlineExceeded wraps an existing error of type Deadline_exceeded with the given message.
func WrapDeadlineExceeded(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeDeadlineExceeded, msg, err)
}

// WrapfDeadlineExceeded wraps an existing error of type Deadline_exceeded with a formatted message.
func WrapfDeadlineExceeded(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeDeadlineExceeded, fmt.Sprintf(format, args...), err)
}

// EnsureDeadlineExceeded ensures the error is an *Error, falling back to Deadline_exceeded with the given message.
func EnsureDeadlineExceeded(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeDeadlineExceeded, msg, err)
}

// EnsurefDeadlineExceeded ensures the error is an *Error, falling back to Deadline_exceeded with a formatted message.
func EnsurefDeadlineExceeded(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeDeadlineExceeded, fmt.Sprintf(format, args...), err)
}

// NewNotFound creates a new error of type Not_found with the given message.
func NewNotFound(msg string) *Error {
	return newError(CodeNotFound, msg, nil)
}

// NewfNotFound creates a new error of type Not_found with a formatted message.
func NewfNotFound(format string, args ...any) *Error {
	return newError(CodeNotFound, fmt.Sprintf(format, args...), nil)
}

// WrapNotFound wraps an existing error of type Not_found with the given message.
func WrapNotFound(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeNotFound, msg, err)
}

// WrapfNotFound wraps an existing error of type Not_found with a formatted message.
func WrapfNotFound(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeNotFound, fmt.Sprintf(format, args...), err)
}

// EnsureNotFound ensures the error is an *Error, falling back to Not_found with the given message.
func EnsureNotFound(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeNotFound, msg, err)
}

// EnsurefNotFound ensures the error is an *Error, falling back to Not_found with a formatted message.
func EnsurefNotFound(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeNotFound, fmt.Sprintf(format, args...), err)
}

// NewAlreadyExists creates a new error of type Already_exists with the given message.
func NewAlreadyExists(msg string) *Error {
	return newError(CodeAlreadyExists, msg, nil)
}

// NewfAlreadyExists creates a new error of type Already_exists with a formatted message.
func NewfAlreadyExists(format string, args ...any) *Error {
	return newError(CodeAlreadyExists, fmt.Sprintf(format, args...), nil)
}

// WrapAlreadyExists wraps an existing error of type Already_exists with the given message.
func WrapAlreadyExists(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeAlreadyExists, msg, err)
}

// WrapfAlreadyExists wraps an existing error of type Already_exists with a formatted message.
func WrapfAlreadyExists(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeAlreadyExists, fmt.Sprintf(format, args...), err)
}

// EnsureAlreadyExists ensures the error is an *Error, falling back to Already_exists with the given message.
func EnsureAlreadyExists(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeAlreadyExists, msg, err)
}

// EnsurefAlreadyExists ensures the error is an *Error, falling back to Already_exists with a formatted message.
func EnsurefAlreadyExists(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeAlreadyExists, fmt.Sprintf(format, args...), err)
}

// NewPermissionDenied creates a new error of type Permission_denied with the given message.
func NewPermissionDenied(msg string) *Error {
	return newError(CodePermissionDenied, msg, nil)
}

// NewfPermissionDenied creates a new error of type Permission_denied with a formatted message.
func NewfPermissionDenied(format string, args ...any) *Error {
	return newError(CodePermissionDenied, fmt.Sprintf(format, args...), nil)
}

// WrapPermissionDenied wraps an existing error of type Permission_denied with the given message.
func WrapPermissionDenied(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodePermissionDenied, msg, err)
}

// WrapfPermissionDenied wraps an existing error of type Permission_denied with a formatted message.
func WrapfPermissionDenied(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodePermissionDenied, fmt.Sprintf(format, args...), err)
}

// EnsurePermissionDenied ensures the error is an *Error, falling back to Permission_denied with the given message.
func EnsurePermissionDenied(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodePermissionDenied, msg, err)
}

// EnsurefPermissionDenied ensures the error is an *Error, falling back to Permission_denied with a formatted message.
func EnsurefPermissionDenied(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodePermissionDenied, fmt.Sprintf(format, args...), err)
}

// NewResourceExhausted creates a new error of type Resource_exhausted with the given message.
func NewResourceExhausted(msg string) *Error {
	return newError(CodeResourceExhausted, msg, nil)
}

// NewfResourceExhausted creates a new error of type Resource_exhausted with a formatted message.
func NewfResourceExhausted(format string, args ...any) *Error {
	return newError(CodeResourceExhausted, fmt.Sprintf(format, args...), nil)
}

// WrapResourceExhausted wraps an existing error of type Resource_exhausted with the given message.
func WrapResourceExhausted(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeResourceExhausted, msg, err)
}

// WrapfResourceExhausted wraps an existing error of type Resource_exhausted with a formatted message.
func WrapfResourceExhausted(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeResourceExhausted, fmt.Sprintf(format, args...), err)
}

// EnsureResourceExhausted ensures the error is an *Error, falling back to Resource_exhausted with the given message.
func EnsureResourceExhausted(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeResourceExhausted, msg, err)
}

// EnsurefResourceExhausted ensures the error is an *Error, falling back to Resource_exhausted with a formatted message.
func EnsurefResourceExhausted(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeResourceExhausted, fmt.Sprintf(format, args...), err)
}

// NewFailedPrecondition creates a new error of type Failed_precondition with the given message.
func NewFailedPrecondition(msg string) *Error {
	return newError(CodeFailedPrecondition, msg, nil)
}

// NewfFailedPrecondition creates a new error of type Failed_precondition with a formatted message.
func NewfFailedPrecondition(format string, args ...any) *Error {
	return newError(CodeFailedPrecondition, fmt.Sprintf(format, args...), nil)
}

// WrapFailedPrecondition wraps an existing error of type Failed_precondition with the given message.
func WrapFailedPrecondition(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeFailedPrecondition, msg, err)
}

// WrapfFailedPrecondition wraps an existing error of type Failed_precondition with a formatted message.
func WrapfFailedPrecondition(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeFailedPrecondition, fmt.Sprintf(format, args...), err)
}

// EnsureFailedPrecondition ensures the error is an *Error, falling back to Failed_precondition with the given message.
func EnsureFailedPrecondition(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeFailedPrecondition, msg, err)
}

// EnsurefFailedPrecondition ensures the error is an *Error, falling back to Failed_precondition with a formatted message.
func EnsurefFailedPrecondition(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeFailedPrecondition, fmt.Sprintf(format, args...), err)
}

// NewAborted creates a new error of type Aborted with the given message.
func NewAborted(msg string) *Error {
	return newError(CodeAborted, msg, nil)
}

// NewfAborted creates a new error of type Aborted with a formatted message.
func NewfAborted(format string, args ...any) *Error {
	return newError(CodeAborted, fmt.Sprintf(format, args...), nil)
}

// WrapAborted wraps an existing error of type Aborted with the given message.
func WrapAborted(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeAborted, msg, err)
}

// WrapfAborted wraps an existing error of type Aborted with a formatted message.
func WrapfAborted(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeAborted, fmt.Sprintf(format, args...), err)
}

// EnsureAborted ensures the error is an *Error, falling back to Aborted with the given message.
func EnsureAborted(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeAborted, msg, err)
}

// EnsurefAborted ensures the error is an *Error, falling back to Aborted with a formatted message.
func EnsurefAborted(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeAborted, fmt.Sprintf(format, args...), err)
}

// NewOutOfRange creates a new error of type Out_of_range with the given message.
func NewOutOfRange(msg string) *Error {
	return newError(CodeOutOfRange, msg, nil)
}

// NewfOutOfRange creates a new error of type Out_of_range with a formatted message.
func NewfOutOfRange(format string, args ...any) *Error {
	return newError(CodeOutOfRange, fmt.Sprintf(format, args...), nil)
}

// WrapOutOfRange wraps an existing error of type Out_of_range with the given message.
func WrapOutOfRange(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeOutOfRange, msg, err)
}

// WrapfOutOfRange wraps an existing error of type Out_of_range with a formatted message.
func WrapfOutOfRange(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeOutOfRange, fmt.Sprintf(format, args...), err)
}

// EnsureOutOfRange ensures the error is an *Error, falling back to Out_of_range with the given message.
func EnsureOutOfRange(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeOutOfRange, msg, err)
}

// EnsurefOutOfRange ensures the error is an *Error, falling back to Out_of_range with a formatted message.
func EnsurefOutOfRange(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeOutOfRange, fmt.Sprintf(format, args...), err)
}

// NewUnimplemented creates a new error of type Unimplemented with the given message.
func NewUnimplemented(msg string) *Error {
	return newError(CodeUnimplemented, msg, nil)
}

// NewfUnimplemented creates a new error of type Unimplemented with a formatted message.
func NewfUnimplemented(format string, args ...any) *Error {
	return newError(CodeUnimplemented, fmt.Sprintf(format, args...), nil)
}

// WrapUnimplemented wraps an existing error of type Unimplemented with the given message.
func WrapUnimplemented(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnimplemented, msg, err)
}

// WrapfUnimplemented wraps an existing error of type Unimplemented with a formatted message.
func WrapfUnimplemented(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnimplemented, fmt.Sprintf(format, args...), err)
}

// EnsureUnimplemented ensures the error is an *Error, falling back to Unimplemented with the given message.
func EnsureUnimplemented(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnimplemented, msg, err)
}

// EnsurefUnimplemented ensures the error is an *Error, falling back to Unimplemented with a formatted message.
func EnsurefUnimplemented(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnimplemented, fmt.Sprintf(format, args...), err)
}

// NewInternal creates a new error of type Internal with the given message.
func NewInternal(msg string) *Error {
	return newError(CodeInternal, msg, nil)
}

// NewfInternal creates a new error of type Internal with a formatted message.
func NewfInternal(format string, args ...any) *Error {
	return newError(CodeInternal, fmt.Sprintf(format, args...), nil)
}

// WrapInternal wraps an existing error of type Internal with the given message.
func WrapInternal(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeInternal, msg, err)
}

// WrapfInternal wraps an existing error of type Internal with a formatted message.
func WrapfInternal(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeInternal, fmt.Sprintf(format, args...), err)
}

// EnsureInternal ensures the error is an *Error, falling back to Internal with the given message.
func EnsureInternal(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeInternal, msg, err)
}

// EnsurefInternal ensures the error is an *Error, falling back to Internal with a formatted message.
func EnsurefInternal(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeInternal, fmt.Sprintf(format, args...), err)
}

// NewUnavailable creates a new error of type Unavailable with the given message.
func NewUnavailable(msg string) *Error {
	return newError(CodeUnavailable, msg, nil)
}

// NewfUnavailable creates a new error of type Unavailable with a formatted message.
func NewfUnavailable(format string, args ...any) *Error {
	return newError(CodeUnavailable, fmt.Sprintf(format, args...), nil)
}

// WrapUnavailable wraps an existing error of type Unavailable with the given message.
func WrapUnavailable(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnavailable, msg, err)
}

// WrapfUnavailable wraps an existing error of type Unavailable with a formatted message.
func WrapfUnavailable(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnavailable, fmt.Sprintf(format, args...), err)
}

// EnsureUnavailable ensures the error is an *Error, falling back to Unavailable with the given message.
func EnsureUnavailable(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnavailable, msg, err)
}

// EnsurefUnavailable ensures the error is an *Error, falling back to Unavailable with a formatted message.
func EnsurefUnavailable(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnavailable, fmt.Sprintf(format, args...), err)
}

// NewDataLoss creates a new error of type Data_loss with the given message.
func NewDataLoss(msg string) *Error {
	return newError(CodeDataLoss, msg, nil)
}

// NewfDataLoss creates a new error of type Data_loss with a formatted message.
func NewfDataLoss(format string, args ...any) *Error {
	return newError(CodeDataLoss, fmt.Sprintf(format, args...), nil)
}

// WrapDataLoss wraps an existing error of type Data_loss with the given message.
func WrapDataLoss(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeDataLoss, msg, err)
}

// WrapfDataLoss wraps an existing error of type Data_loss with a formatted message.
func WrapfDataLoss(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeDataLoss, fmt.Sprintf(format, args...), err)
}

// EnsureDataLoss ensures the error is an *Error, falling back to Data_loss with the given message.
func EnsureDataLoss(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeDataLoss, msg, err)
}

// EnsurefDataLoss ensures the error is an *Error, falling back to Data_loss with a formatted message.
func EnsurefDataLoss(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeDataLoss, fmt.Sprintf(format, args...), err)
}

// NewUnauthenticated creates a new error of type Unauthenticated with the given message.
func NewUnauthenticated(msg string) *Error {
	return newError(CodeUnauthenticated, msg, nil)
}

// NewfUnauthenticated creates a new error of type Unauthenticated with a formatted message.
func NewfUnauthenticated(format string, args ...any) *Error {
	return newError(CodeUnauthenticated, fmt.Sprintf(format, args...), nil)
}

// WrapUnauthenticated wraps an existing error of type Unauthenticated with the given message.
func WrapUnauthenticated(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnauthenticated, msg, err)
}

// WrapfUnauthenticated wraps an existing error of type Unauthenticated with a formatted message.
func WrapfUnauthenticated(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	return newError(CodeUnauthenticated, fmt.Sprintf(format, args...), err)
}

// EnsureUnauthenticated ensures the error is an *Error, falling back to Unauthenticated with the given message.
func EnsureUnauthenticated(err error, msg string) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnauthenticated, msg, err)
}

// EnsurefUnauthenticated ensures the error is an *Error, falling back to Unauthenticated with a formatted message.
func EnsurefUnauthenticated(err error, format string, args ...any) *Error {
	if err == nil {
		return nil
	}
	if e, ok := As(err); ok {
		return e
	}
	return newError(CodeUnauthenticated, fmt.Sprintf(format, args...), err)
}
